### ISSUE TITLE
Reahl help-commands returns an exception

### ISSUE THREAD

**Issue by cannatag** [reahl/reahl#117]
When I try ``reahl help-commands`` I get the following output:
```
(reahl - 3.6.5) PS C:\Python\VirtualEnvs\reahl - 3.6.5> reahl help-commands
usage: reahl [-h] [-l {CRITICAL,ERROR,WARNING,INFO,DEBUG}] command ...

Invoke reahl commands on the commandline.

positional arguments:
  command               a command
  command_args

optional arguments:
  -h, --help            show this help message and exit
  -l {CRITICAL,ERROR,WARNING,INFO,DEBUG}, --loglevel {CRITICAL,ERROR,WARNING,INFO,DEBUG}
                        set log level to this

"reahl help-commands" gives a list of available commands


Commands: ( reahl <command> --help for usage on a specific command)

addlocale            Adds a new locale catalog.
alias                Adds an alias.
backupall            Backs up all the databases on the host this project config points to.
backupdb             Backs up the database.
build                Builds all distributable packages for each project in the current selection.
checkconfig          Checks current configuration settings.
clearselection       Clears the current selection.
compiletranslations  Compiles all current translations.
createdb             Creates the database.
createdbtables       Creates all necessary tables in the database.
createdbuser         Creates the database user.
debianise            Debianises a project.
debinstall           Runs setup.py install with correct arguments for packaging the result in a deb (for each project in the selection).
delete               Deletes the saved selection set with the given name.
diffdb               Prints out a diff between the current database schema and what is expected by the current code.
dropdb               Drops the database.
dropdbtables         Drops all necessary tables in the database.
dropdbuser           Drops the database user.
example              Give you a copy of an example.
explainlegend        Prints an explanation of project status indicators.
extractmessages      Collects strings marked for translation.
info                 Prints information about a project.
list                 Lists all the projects currently selected (or, optionally, all projects in the workspace)
listconfig           Lists current configuration settings.
listdeps             List all dependency eggs in dependency order.
listexamples         Lists available examples.
markreleased         Marks each project in the current selection as released.
mergetranslations    Merges newly discovered strings needing translation with a catalog of existing translations.
migratedb            Runs all necessary database migrations.
missingdeps          Lists all missing thirdparty dependencies for each project in the current selection.
read                 Changes the current selection to the named, previously saved selection.
refresh              Reconstructs the working set of projects by searching through the given directories (by default the entire workspace directory).
restoreall           Restores all the databases on the host this project config points to.
restoredb            Restores the database.
runjobs              Runs all registered scripts.
save                 Saves the current selection of projects using the given name.
select               Selects a subset of projects in the workspace based on their state.
selections           Lists all the named sets of selections that have been saved previously.
serve                Serves the project configured in the given directory (defaults to ./etc).
servesmtp            Runs an SMTP server on port 8025 for testing.
setup                Runs setup.py <command> for each project in the current selection.
shell                Executes a shell command in each selected project, from each project's own root directory.
sizedb               Prints the current size of the database.
substvars            Generates debian substvars.
syncfiles            Uses the sitecopy program to upload / sync static files to a remote webserver.
unalias              Removes an alias.
update-copyright     Updates the dates found in copyright statements found on the first line of files based on git history.
updateapt            Updates the index files of the given apt repository.
upload               Uploads all built distributable packages for each project in the current selection.
Traceback (most recent call last):
  File "c:\python\virtualenvs\reahl - 3.6.5\lib\site-packages\reahl\component\shelltools.py", line 159, in execute
    command = self.command_named(args.command)
  File "c:\python\virtualenvs\reahl - 3.6.5\lib\site-packages\reahl\component\shelltools.py", line 149, in command_named
    raise CommandNotFound(name)
reahl.component.shelltools.CommandNotFound: help-commands

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\VirtualEnvs\reahl - 3.6.5\Scripts\reahl.exe\__main__.py", line 9, in <module>
  File "c:\python\virtualenvs\reahl - 3.6.5\lib\site-packages\reahl\component\shelltools.py", line 208, in execute_one
    result = cls(sys.argv[0]).do(sys.argv[1:])
  File "c:\python\virtualenvs\reahl - 3.6.5\lib\site-packages\reahl\component\shelltools.py", line 110, in do
    return self.execute(args)
  File "c:\python\virtualenvs\reahl - 3.6.5\lib\site-packages\reahl\component\shelltools.py", line 234, in execute
    return super(ReahlCommandline, self).execute(args)
  File "c:\python\virtualenvs\reahl - 3.6.5\lib\site-packages\reahl\component\shelltools.py", line 165, in execute
    self.print_help(out_stream)
  File "c:\python\virtualenvs\reahl - 3.6.5\lib\site-packages\reahl\component\shelltools.py", line 239, in print_help
    max_len = max([len(alias_name) for alias_name in self.aliasses.keys()])
ValueError: max() arg is an empty sequence
```
It seems that the ``help-commands`` command is missing from the available commands. I'm on Windows 10 version 1803.

**Comment by craig-reahl** [comment]
Thanks again @cannatag 

I can confirm that I am also getting the same output on linux. 

Although the 

> help-commands

 result is displayed, the trailing stack trace it is annoying.I will have a look at it today.

Craig.

**Comment by craig-reahl** [comment]
Certified bug.

## How to reproduce:
By running the following command and not having any global or local _**reahlalias**_ defined:
`reahl help-commands`

## Fix:
Fix needs to be released. (version > Reahl-4.0.0)

## Workaround:
Define a local _**reahlalias**_ in your project like so (this is just a noop):
`reahl alias -l unit setup -- check`
or, since its good practice to have tests, a more meaningful one like we have for one of our examples:
`reahl alias -l unit setup -- -q pytest --addopts '-s --pyargs basichtmlwidgets.basichtmlinputs_dev' `
This creates an alias called unit so that you can run your tests like so:
`reahl unit`
