### ISSUE TITLE
error running examples - DistributionNotFound

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#14]
I installed reahl and got the hello tutorial working. But when I use reahl example tutorial.pageflow1, then cd into the pageflow1 to run reahl server etc, I got:

Using config from etc

WARNING:reahl.component.config:reahlsystem.connection_uri in etc/reahl.config.py is using a dangerous default setting: sqlite:////tmp/reahl.db
WARNING:reahl.component.config:reahlsystem.root_egg in etc/reahl.config.py is using a dangerous default setting: pageflow1
Traceback (most recent call last):
  File "/opt/venv/reahl/bin/reahl", line 9, in <module>
    load_entry_point('reahl-dev==2.1.0', 'console_scripts', 'reahl')()
  File "/opt/venv/reahl/lib/python2.7/site-packages/reahl_component-2.1.0-py2.7.egg/reahl/component/shelltools.py", line 164, in execute_one
    return_code = commandline.execute_command(command, line, options, parser)
  File "build/bdist.linux-x86_64/egg/reahl/dev/devshell.py", line 546, in execute_command
  File "/opt/venv/reahl/lib/python2.7/site-packages/reahl_component-2.1.0-py2.7.egg/reahl/component/shelltools.py", line 106, in do
    return self.execute(options, args)
  File "build/bdist.linux-x86_64/egg/reahl/webdev/commands.py", line 39, in execute
    import warnings
  File "build/bdist.linux-x86_64/egg/reahl/webdev/commands.py", line 51, in start_server

  File "build/bdist.linux-x86_64/egg/reahl/webdev/webserver.py", line 266, in fromConfigDirectory
  File "/opt/venv/reahl/lib/python2.7/site-packages/reahl_component-2.1.0-py2.7.egg/reahl/component/config.py", line 270, in configure
    require(self.reahlsystem.root_egg)
  File "/opt/venv/reahl/local/lib/python2.7/site-packages/pkg_resources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/venv/reahl/local/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pageflow1

I tried other examples with similar results.

Thanks,

---

Imported from Launchpad using lp2gh.
- date created: 2014-05-23T14:37:40Z
- owner: hyao
- the launchpad url was https://bugs.launchpad.net/bugs/1322652

**Comment by IwanVosloo** [comment]
(by iv)
Hi there Heling,

Did you run "reahl setup -- develop -N" from inside such an example directory, before trying to "reahl serve" ?

Regards
-Iwan

**Comment by IwanVosloo** [comment]
(by hyao)
Hi Iwan,

When I tried to run "reahl setup -- develop -N" from the example dir, I got:

WARNING:root:DEPRECATED: <function define_main_window at 0x7f15c1cf76e0>. Please use .define_page() instead.
WARNING:root:DEPRECATED: <function define_region at 0x7f15c1cf7cf8>. Please use .define_user_interface() instead
WARNING:root:DEPRECATED: <function define_regex_region at 0x7f15c1cf7de8>. Please use .define_regex_user_interface() instead
WARNING:root:DEPRECATED: <class 'reahl.web.fw.Region'>. Region has been renamed to UserInterface, please use UserInterface instead
WARNING:root:DEPRECATED: <class 'reahl.web.fw.ReahlWebApplication'>. ReahlWebApplication has been renamed to ReahlWSGIApplication, please use ReahlWSGIApplication instead
Traceback (most recent call last):
  File "/opt/venv/reahl/bin/reahl", line 9, in <module>
    load_entry_point('reahl-dev==2.1.0', 'console_scripts', 'reahl')()
  File "/opt/venv/reahl/lib/python2.7/site-packages/reahl_component-2.1.0-py2.7.egg/reahl/component/shelltools.py", line 164, in execute_one
    return_code = commandline.execute_command(command, line, options, parser)
  File "build/bdist.linux-x86_64/egg/reahl/dev/devshell.py", line 546, in execute_command
  File "/opt/venv/reahl/lib/python2.7/site-packages/reahl_component-2.1.0-py2.7.egg/reahl/component/shelltools.py", line 106, in do
    return self.execute(options, args)
  File "build/bdist.linux-x86_64/egg/reahl/dev/devshell.py", line 371, in execute
  File "build/bdist.linux-x86_64/egg/reahl/dev/devshell.py", line 258, in execute
  File "build/bdist.linux-x86_64/egg/reahl/dev/devshell.py", line 208, in execute_one
  File "build/bdist.linux-x86_64/egg/reahl/dev/devshell.py", line 404, in function
  File "build/bdist.linux-x86_64/egg/reahl/dev/devdomain.py", line 1640, in setup
  File "build/bdist.linux-x86_64/egg/reahl/dev/devdomain.py", line 1684, in run_deps_for_setup
  File "build/bdist.linux-x86_64/egg/reahl/dev/devdomain.py", line 537, in as_string_for_egg
  File "build/bdist.linux-x86_64/egg/reahl/dev/devdomain.py", line 573, in version_is_available
  File "build/bdist.linux-x86_64/egg/reahl/dev/devdomain.py", line 558, in is_internal
AttributeError: 'EggProject' object has no attribute 'contains_project_named'

I tried a few other examples with the same result.

By the way, could you add the "reahl setup -- develop -N" to the "checking out an example" section on:

http://www.reahl.org/docs/current/tutorial/gettingstarted-develop.d.html#checking-out-an-example

Thanks,

**Comment by IwanVosloo** [comment]
(by iv)
Hi Heling,

Thanks. "reahl setup -- develop -N" is explained here: http://www.reahl.org/docs/current/tutorial/gettingstarted-develop.d.html#preparing-for-development

But, we will add another mention where you suggest.

Can you please give me the output of the following command, if you execute it from the directory in which you experience this last error:

ls {./,../,.../}.reahlproject

Thank you
- Iwan

**Comment by IwanVosloo** [comment]
(by hyao)
Hi IWan,

I got it. I shouldn't nest the project dir inside another project.

I move the example to a new dir (not inside another reahl project dir). It runs now and looks very nice!

Thank you very much,

Heling

**Comment by IwanVosloo** [comment]
(by iv)
Hi Heling.

I am glad your problem is solved.

Your first issue is something we could perhaps report better (with a hint)...

The second is a genuine bug though - I am splitting that out into a separate item. It should not break because projects are nested.

Thanks for your input.
- Iwan
