### ISSUE TITLE
Please make app deployment documentation on location more explicit

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#144]
[The configure section of the docs](https://www.reahl.org/docs/4.0/tutorial/deployment.d.html#configure) on how to deploy an app state:

1. An application in production should not have any “dangerous default” settings. 
1. The helloanywhere example contains the necessary production config in its prod/etc directory.
1. Head over to PythonAnywhere again, to the “Files” tab and create an etc directory inside your home directory. 
1. Upload the config files from the example’s prod/etc to that new directory.

It is the last statement that is confusing.  Where can I find the example? If you are talking about on my home machine, there is an etc directory but no `prod\etc` directory.

I did upload the `web.config.py` file in the etc directory on my home machine to the etc directory I created at Python anywhere. 

```
(simpletr) 06:58 ~ $ reahl createdb etc
WARNING:reahl.component.config:reahlsystem.connection_uri in etc/reahl.config.py is using a dangerous default setting: sqlite:////tmp/reahl.db
WARNING:reahl.component.config:reahlsystem.debug in etc/reahl.config.py is using a dangerous default setting: True
WARNING:reahl.component.config:reahlsystem.root_egg in etc/reahl.config.py is using a dangerous default setting: metaperl
Traceback (most recent call last):
  File "/home/metaperl/.virtualenvs/simpletr/bin/reahl", line 11, in <module>
    sys.exit(ReahlCommandline.execute_one())
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 208, in execute_one
    result = cls().do(sys.argv[1:])
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 110, in do
    return self.execute(args)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 234, in execute
    return super(ReahlCommandline, self).execute(args)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 169, in execute
    return command.do(args.command_args)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 110, in do
    return self.execute(args)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/commands/prodshell.py", line 172, in execute
    super(CreateDB, self).execute(args)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/commands/prodshell.py", line 41, in execute
    self.create_context(args.config_directory)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/commands/prodshell.py", line 46, in create_context
    self.context = ExecutionContext.for_config_directory(config_directory)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/context.py", line 44, in for_config_directory
    config.configure()
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/config.py", line 279, in configure
    require(self.reahlsystem.root_egg)
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: <exception str() failed>
(simpletr) 06:58 ~ $
```

**Comment by IwanVosloo** [comment]
If I do a "reahl example tutorial.helloanywhere" it creates a helloanywhere/prod/etc directory with the necessary files. 

Can you post a directory listing of what you get when you do "reahl example tutorial.helloanywhere" ?

**Comment by metaperl** [comment]
OK, what you suggested works fine. I am not trying to deploy helloanywhere. I am trying to deploy my simple app... 

I copied the `prod\etc` config files from helloworldanywhere but I am getting an error when trying to create the db:

```
(simpletr) 07:54 ~ $ reahl createdb etc                                                                                             
Traceback (most recent call last):                                                                                                  
  File "/home/metaperl/.virtualenvs/simpletr/bin/reahl", line 11, in <module>                                                       
    sys.exit(ReahlCommandline.execute_one())                                                                                        
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 208, in execute_one   
    result = cls().do(sys.argv[1:])                                                                                                 
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 110, in do            
    return self.execute(args)                                                                                                       
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 234, in execute       
    return super(ReahlCommandline, self).execute(args)                                                                              
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 169, in execute       
    return command.do(args.command_args)                                                                                            
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/shelltools.py", line 110, in do            
    return self.execute(args)                                                                                                       
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/commands/prodshell.py", line 172, in execute         
    super(CreateDB, self).execute(args)                                                                                             
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/commands/prodshell.py", line 41, in execute          
    self.create_context(args.config_directory)                                                                                      
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/commands/prodshell.py", line 51, in create_context   
    self.context.system_control = SystemControl(self.context.config)                                                                
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/dbutils.py", line 75, in __init__          
    self.db_control = self.db_control_for_uri(self.connection_uri)                                                                  
  File "/home/metaperl/.virtualenvs/simpletr/lib/python3.5/site-packages/reahl/component/dbutils.py", line 129, in db_control_for_uri                                                                                                                                   
    raise CouldNotFindDatabaseControlException(url)                                                                                 
reahl.component.dbutils.CouldNotFindDatabaseControlException: sqlite://///home/metaperl/simple_tr.db                                
(simpletr) 07:54 ~ $ ls /home/metaperl/*.db                                                                                         
/home/metaperl/simple_tr.db  /home/metaperl/simpletr.db                                                                             
(simpletr) 07:54 ~ $                                   
```

Here is reahl.config.py - https://www.pythonanywhere.com/user/metaperl/shares/32e610aae39a402eaadaac2a5b411dde/

This is web.config.py - 
https://www.pythonanywhere.com/user/metaperl/shares/6a7e749dd1f440f28fb619fa702577d0/

**Comment by metaperl** [comment]
I've done some debugging of this. The function `db_control_for_uri` is being passed the URL `sqlite:////home/metaperl/simple_tr.db`

but the attempt to iterate through `self.config.reahlsystem.databasecontrols` only yields `<class 'reahl.component.dbutils.NullDatabaseControl'>   ` so there is no match.

**Comment by metaperl** [comment]
I find it odd that `reahl createdbuser` is not one of the steps mentioned in [deployment](https://www.reahl.org/docs/4.0/tutorial/deployment.d.html#configure). I'm going to create a fresh environment and try to install just the example program.

**Comment by metaperl** [comment]
I figured it out. I left out a dependency in .reahlproject:

        <egg name="reahl-sqlitesupport"/>

Now it runs into the dangerous mailport issue. So I commented out the danger check and I have an app working at http://metalevel.pythonanywhere.com/

**Comment by IwanVosloo** [comment]
Great! 

Sorry, I did not read that stacktrace properly, I was on my way to the airport. Yes the databases become available only when you depend on one of them.

However, the dangerous mail port is not an issue. We try to default settings where we can, but some of these are not suitable for production. For these we issue that warning. But it is only a warning.

If you want the warning to go away, just specify a value for that setting. I assume you are talking about mail.smtp_port ?

**Comment by IwanVosloo** [comment]
Oh, I see now, those warnings turn into exceptions in the case where we realise you are not using the usual development webserver. I answered in #145

**Comment by IwanVosloo** [comment]
Just on your comment:

> I find it odd that reahl createdbuser is not one of the steps mentioned in deployment. I'm going to create a fresh environment and try to install just the example program.

We need to investigate this bit. I think its was probably left out because if you use, say, a mysql database on PythonAnywhere, they create it for you (or you create it via some panel). Will have to double-check this and sync with the example and ifs config.

**Comment by IwanVosloo** [comment]
Ah, actually, the oddity is because:

The example is using sqlite, and sqlite does not need a user to be created.
