### ISSUE TITLE
`reahl servesmtp` yields TypeError: execute() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#160]
In attempting to run [tutorial.login2bootstrap](https://www.reahl.org/docs/4.0/tutorial/loggingin.d.html#re-using-the-user-interface-as-well), I executed `reahl servesmtp` and got this error trace:

```bash
c:\Users\i2615\AppData\Roaming\tmp>reahl servesmtp
reahl servesmtp
REAHLWORKSPACE environment variable not set, defaulting to C:\Users\i2615
Traceback (most recent call last):
  File "c:\development\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\development\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Development\Scripts\reahl.exe\__main__.py", line 9, in <module>
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 208, in execute_one
    result = cls().do(sys.argv[1:])
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 110, in do
    return self.execute(args)
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 234, in execute
    return super(ReahlCommandline, self).execute(args)
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 169, in execute
    return command.do(args.command_args)
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 110, in do
    return self.execute(args)
TypeError: execute() missing 1 required positional argument: 'args'

c:\Users\i2615\AppData\Roaming\tmp>

```

**Comment by metaperl** [comment]
[SMTP Faker](https://pypi.org/project/smtp_faker/) actually got me to the point where I need to verify the registered account. Thing is, SMTP faker didnt echo the incoming email, so I wasnt able to click on a verify link. 

I'm trying to see how to update the database tables so the user is verified.

**Comment by metaperl** [comment]
`DELETE FROM activateaccount WHERE system_account_id = 1;` did not remove the verification requirement.

**Comment by metaperl** [comment]
Success:
```sql
UPDATE systemaccount SET registration_date=DATETIME('now'), account_enabled=1, failed_logins=0;
```

**Comment by IwanVosloo** [comment]
This is an unfortunate one. Its tricky to get nice test coverage there.

What you can do as a workaround until we release a fix, is to run the following Python script:

```import asyncore

from reahl.dev.mailtest import EchoSMTPServer

EchoSMTPServer()
print("Running Echo SMTP Server on port 8025, type [ctrl-c] to exit.")
try:
            asyncore.loop()
except KeyboardInterrupt:
            pass

```

**Comment by metaperl** [comment]
OK, just FYI [asyncore is deprecated in Python 3](https://docs.python.org/3.6/library/asyncore.html)

**Comment by IwanVosloo** [comment]
Thanks for the heads up. As part of fixing this we should then get off asyncore as well.
