### ISSUE TITLE
No "port in use" exception when `reahl serve etc` is run on 2 different tutorials

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#168]
There is no exception thrown when `reahl serve etc` is run from a second example while a first example is running. As a result [my earlier reported issue](https://github.com/reahl/reahl/issues/166) which I reported occured on numerous tutorials may not have occurred on each.

**Comment by IwanVosloo** [comment]
That is strange. Is this on cygwyn?

In our vagrant ubuntu box, I get:

```
Traceback (most recent call last):
  File "/vagrant/reahl-webdev/reahl/webdev/webserver.py", line 463, in __init__
    self.httpd = ReahlWSGIServer.make_server('', port, self.reahl_wsgi_app)
  File "/vagrant/reahl-webdev/reahl/webdev/webserver.py", line 190, in make_server
    handler_class=SingleWSGIRequestHandler)
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/vagrant/reahl-webdev/reahl/webdev/webserver.py", line 194, in __init__
    simple_server.WSGIServer.__init__(self, server_address, RequestHandlerClass)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/python3.6/bin/reahl", line 11, in <module>
    load_entry_point('reahl-component', 'console_scripts', 'reahl')()
  File "/vagrant/reahl-component/reahl/component/shelltools.py", line 208, in execute_one
    result = cls().do(sys.argv[1:])
  File "/vagrant/reahl-component/reahl/component/shelltools.py", line 110, in do
    return self.execute(args)
  File "/vagrant/reahl-component/reahl/component/shelltools.py", line 234, in execute
    return super(ReahlCommandline, self).execute(args)
  File "/vagrant/reahl-component/reahl/component/shelltools.py", line 169, in execute
    return command.do(args.command_args)
  File "/vagrant/reahl-component/reahl/component/shelltools.py", line 110, in do
    return self.execute(args)
  File "/vagrant/reahl-webdev/reahl/webdev/commands.py", line 70, in execute
    reahl_server = ReahlWebServer.fromConfigDirectory(config_directory, args.port)
  File "/vagrant/reahl-webdev/reahl/webdev/webserver.py", line 444, in fromConfigDirectory
    return cls(config, port)
  File "/vagrant/reahl-webdev/reahl/webdev/webserver.py", line 469, in __init__
    raise AssertionError(message)
AssertionError: Caught socket.error: [Errno 98] Address already in use
This means that another process is using one of these ports: 8000, 8363. 
If this happens while running tests, it probably means that a browser client did not close its side of a connection to a previous server you had running - and that the server socket now sits in TIME_WAIT state. Is there perhaps a browser hanging around from a previous run? I have no idea how to fix this automatically... see http://hea-www.harvard.edu/~fine/Tech/addrinuse.html
```

**Comment by metaperl** [comment]
No it's on Windows 10. I just tried it and I can verify that no such exception is thrown.

**Comment by craig-reahl** [comment]
I don't think the issue is related to [reahl](www.reahl.org). I replicated the scenario by running a simple http server bound to the same port in two different shells(in windows 10):

`python3 -m http.server`

The first process that bound to the port was the one serving the requests. If I shut first one down, the other would continue serving requests.

**Comment by IwanVosloo** [comment]
Ok, so it seems like the windows libraries have different semantics.
Perhaps the question is, can we emulate the linux behaviour on windows without it being a lot of effort?

If its easy we might consider doing it... because it could prevent confusion for newcomers running the examples on Windows.
