### ISSUE TITLE
AssertionError: The schema for the "reahl-web-declarative" egg has already been created previously at version 4.0.2

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#173]
Related to https://github.com/reahl/reahl/issues/141

I created a completely fresh install of an example within a virtual environment that I use for all my reahl development work. And an exception was thrown on `reahl createdbtables etc`.

```bash

(reahl_env) c:\prg>reahl example tutorial.sessionscopebootstrap
reahl example tutorial.sessionscopebootstrap
REAHLWORKSPACE environment variable not set, defaulting to C:\Users\i2615
Checking out to c:\prg\sessionscopebootstrap
c:\prg\sessionscopebootstrap\.reahlalias
c:\prg\sessionscopebootstrap\.reahlproject
c:\prg\sessionscopebootstrap\sessionscopebootstrap.py
c:\prg\sessionscopebootstrap\etc\web.config.py
c:\prg\sessionscopebootstrap\sessionscopebootstrap_dev\test_sessionscopebootstrap.py
c:\prg\sessionscopebootstrap\sessionscopebootstrap_dev\__init__.py

(reahl_env) c:\prg>cd sessionscopebootstrap/
cd sessionscopebootstrap/

(reahl_env) c:\prg\sessionscopebootstrap>reahl setup -- develop -N
reahl setup -- develop -N
running develop
running egg_info
creating sessionscopebootstrap.egg-info
writing sessionscopebootstrap.egg-info\PKG-INFO
writing dependency_links to sessionscopebootstrap.egg-info\dependency_links.txt
writing entry points to sessionscopebootstrap.egg-info\entry_points.txt
writing namespace_packages to sessionscopebootstrap.egg-info\namespace_packages.txt
writing requirements to sessionscopebootstrap.egg-info\requires.txt
writing top-level names to sessionscopebootstrap.egg-info\top_level.txt
writing manifest file 'sessionscopebootstrap.egg-info\SOURCES.txt'
reading manifest file 'sessionscopebootstrap.egg-info\SOURCES.txt'
writing manifest file 'sessionscopebootstrap.egg-info\SOURCES.txt'
running build_ext
Creating c:\prg\reahl_env\lib\site-packages\sessionscopebootstrap.egg-link (link to .)
sessionscopebootstrap 0.0 is already the active version in easy-install.pth

Installed c:\prg\sessionscopebootstrap
REAHLWORKSPACE environment variable not set, defaulting to C:\Users\i2615
Performing post command duties 

(reahl_env) c:\prg\sessionscopebootstrap>reahl createdbuser etc
reahl createdbuser etc
WARNING:reahl.component.config:reahlsystem.connection_uri in etc\reahl.config.py is using a dangerous default setting: sqlite:///C:\Users\i2615\AppData\Local\Temp\reahl.db
WARNING:reahl.component.config:reahlsystem.debug in etc\reahl.config.py is using a dangerous default setting: True
WARNING:reahl.component.config:reahlsystem.root_egg in etc\reahl.config.py is using a dangerous default setting: sessionscopebootstrap
WARNING:reahl.component.config:web.default_http_port in etc\web.config.py is using a dangerous default setting: 8000
WARNING:reahl.component.config:web.encrypted_http_port in etc\web.config.py is using a dangerous default setting: 8363
WARNING:reahl.component.config:web.static_root in etc\web.config.py is using a dangerous default setting: c:\prg\sessionscopebootstrap

(reahl_env) c:\prg\sessionscopebootstrap>reahl createdb etc
reahl createdb etc
WARNING:reahl.component.config:reahlsystem.connection_uri in etc\reahl.config.py is using a dangerous default setting: sqlite:///C:\Users\i2615\AppData\Local\Temp\reahl.db
WARNING:reahl.component.config:reahlsystem.debug in etc\reahl.config.py is using a dangerous default setting: True
WARNING:reahl.component.config:reahlsystem.root_egg in etc\reahl.config.py is using a dangerous default setting: sessionscopebootstrap
WARNING:reahl.component.config:web.default_http_port in etc\web.config.py is using a dangerous default setting: 8000
WARNING:reahl.component.config:web.encrypted_http_port in etc\web.config.py is using a dangerous default setting: 8363
WARNING:reahl.component.config:web.static_root in etc\web.config.py is using a dangerous default setting: c:\prg\sessionscopebootstrap

(reahl_env) c:\prg\sessionscopebootstrap>reahl createdbtables etc
reahl createdbtables etc
WARNING:reahl.component.config:reahlsystem.connection_uri in etc\reahl.config.py is using a dangerous default setting: sqlite:///C:\Users\i2615\AppData\Local\Temp\reahl.db
WARNING:reahl.component.config:reahlsystem.debug in etc\reahl.config.py is using a dangerous default setting: True
WARNING:reahl.component.config:reahlsystem.root_egg in etc\reahl.config.py is using a dangerous default setting: sessionscopebootstrap
WARNING:reahl.component.config:web.default_http_port in etc\web.config.py is using a dangerous default setting: 8000
WARNING:reahl.component.config:web.encrypted_http_port in etc\web.config.py is using a dangerous default setting: 8363
WARNING:reahl.component.config:web.static_root in etc\web.config.py is using a dangerous default setting: c:\prg\sessionscopebootstrap
Traceback (most recent call last):
  File "c:\development\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\development\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\prg\reahl_env\Scripts\reahl.exe\__main__.py", line 9, in <module>
  File "c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py", line 208, in execute_one
    result = cls().do(sys.argv[1:])
  File "c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py", line 110, in do
    return self.execute(args)
  File "c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py", line 234, in execute
    return super(ReahlCommandline, self).execute(args)
  File "c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py", line 169, in execute
    return command.do(args.command_args)
  File "c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py", line 110, in do
    return self.execute(args)
  File "c:\prg\reahl_env\lib\site-packages\reahl\commands\prodshell.py", line 250, in execute
    return self.sys_control.create_db_tables()
  File "c:\prg\reahl_env\lib\site-packages\reahl\component\dbutils.py", line 143, in create_db_tables
    return self.orm_control.create_db_tables(transaction, eggs_in_order)
  File "c:\prg\reahl_env\lib\site-packages\reahl\sqlalchemysupport\sqlalchemysupport.py", line 321, in create_db_tables
    self.initialise_schema_version_for(egg)
  File "c:\prg\reahl_env\lib\site-packages\reahl\sqlalchemysupport\sqlalchemysupport.py", line 345, in initialise_schema_version_for
    (egg_name, existing_versions.one().version)
AssertionError: The schema for the "reahl-web-declarative" egg has already been created previously at version 4.0.2

(reahl_env) c:\prg\sessionscopebootstrap>

```

**Comment by IwanVosloo** [comment]
As mentioned in #141 this is because all examples use the same database.
A solution to this is under discussion in #167, lets keep it there.
