### ISSUE TITLE
AttributeError: 'StoredConfiguration' object has no attribute 'accounts'

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#209]
When running this in production on AWS I got the error mentioned in the title. 

```



mod_wsgi (pid=2387): Exception occurred processing WSGI script '/opt/python/current/app/application.py'.
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 2708, in __call__
    response = resource.handle_request(request)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 1893, in handle_request
    return method_handler(request)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 2240, in handle_post
    return self.handle_get_or_post(request, request.POST)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 2230, in handle_get_or_post
    return_value, caught_exception = self.call_with_input(input_values, result.catch_exception)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 2205, in call_with_input
    return_value = self.callable_object(**self.parse_arguments(input_values))
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 2291, in delegate_event
    return self.controller.handle_event(event)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 389, in handle_event
    event_ocurrence.fire() # should only happen if a handler was found
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/component/modelinterface.py", line 1020, in fire
    return self.action(self)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/component/modelinterface.py", line 937, in __call__
    return super(Action, self).__call__(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/component/modelinterface.py", line 903, in __call__
    return self.declared_method(*args_to_send, **kwargs_to_send)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/domain/systemaccountmodel.py", line 349, in register
    return EmailAndPasswordSystemAccount.register(self.email, self.password)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/domain/systemaccountmodel.py", line 179, in register
    return EmailAndPasswordSystemAccount.reserve(email, password, None)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/domain/systemaccountmodel.py", line 193, in reserve
    requirements=[verification_request])
  File "<string>", line 4, in __init__
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/state.py", line 424, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/state.py", line 421, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/domain/systemaccountmodel.py", line 544, in __init__
    deadline = datetime.now() + timedelta(days=config.accounts.request_verification_timeout)
AttributeError: 'StoredConfiguration' object has no attribute 'accounts'

```

But the odd thing is that I did not get this error when running locally. And I do not have a config file named `accounts.config.py` locally. Furthermore, adding an `account.config.py` file in the config directory sibling to my web.config.py` and `reahl.config.py` did not lead to binding of the value `.accounts.request_verification_timeout`.

**Comment by metaperl** [comment]
Apparently [SystemAccountConfig](https://github.com/reahl/reahl/blob/master/reahl-domain/reahl/domain/systemaccountmodel.py#L45) defines the value  `accounts.request_verification_timeout` but for some reason this SystemAccountConfig variable is not inherited when `EmailAndPasswordAccount` tries to configure itself.

**Comment by IwanVosloo** [comment]
> But the odd thing is that I did not get this error when running locally. And I do not have a config file named accounts.config.py locally. Furthermore, adding an account.config.py file in the config directory sibling to my web.config.pyandreahl.config.pydid not lead to binding of the value.accounts.request_verification_timeout`.

Config files are not read simply because they are present in the config directory.
We traverse all dependencies from your reahlsystem.root_egg setting, and read config for each dependency in order.

So, it might be that you are missing a dependency on reahl-domain somehow. (Note that if you are, say, dependent on reahl-domainui, which is in turn dependent on reahl-domain, you should be fine.)

Of course, your setup develop -N should also have done its work.
