### ISSUE TITLE
ValueError: unknown locale: UTF-8 in Python

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#221]
Apparently some Mac users run into the above error.

This is a known issue with Python on the Mac, the simple fix being to export LC_ALL and  LANG to valid  values, as described in: https://wiert.me/2016/05/03/mac-os-x-and-python-valueerror-unknown-locale-utf-8/

We should perhaps mention it in the tutorial docs or Mac install docs.

**Comment by craig-reahl** [comment]
Indeed,

I reproduced the error:

```
(reahl_env) iSparky:parameterised2 craig$ reahl createdbtables etc
WARNING:reahl.component.config:reahlsystem.connection_uri has been defaulted to a value not suitable for production use: "DeferredDefault(default=DeferredDefault(lambda c: 'sqlite:///%s.db' % (os.path.join(os.getcwd(), Requirement.parse(c.root_egg).project_name))), dangerous=True))". You can set it in etc/reahl.config.py
WARNING:reahl.component.config:reahlsystem.debug has been defaulted to a value not suitable for production use: "True". You can set it in etc/reahl.config.py
WARNING:reahl.component.config:reahlsystem.root_egg has been defaulted to a value not suitable for production use: "parameterised2". You can set it in etc/reahl.config.py
Traceback (most recent call last):
  File "/Users/craig/VirtualEnvs/reahl_env/bin/reahl", line 11, in <module>
    sys.exit(ReahlCommandline.execute_one())
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/shelltools.py", line 208, in execute_one
    result = cls().do(sys.argv[1:])
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/shelltools.py", line 110, in do
    return self.execute(args)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/shelltools.py", line 234, in execute
    return super(ReahlCommandline, self).execute(args)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/shelltools.py", line 169, in execute
    return command.do(args.command_args)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/shelltools.py", line 110, in do
    return self.execute(args)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/commands/prodshell.py", line 252, in execute
    super(CreateDBTables, self).execute(args)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/commands/prodshell.py", line 46, in execute
    self.create_context(args.config_directory)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/commands/prodshell.py", line 51, in create_context
    self.context = ExecutionContext.for_config_directory(config_directory)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/context.py", line 44, in for_config_directory
    config.configure()
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/config.py", line 309, in configure
    self.configure_components()
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/config.py", line 326, in configure_components
    egg.read_config(self)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/eggs.py", line 135, in read_config
    config.read(self.configuration_spec)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/component/config.py", line 348, in read
    exec(compile(f.read(), file_path, 'exec'), globals(), locals_dict)
  File "etc/web.config.py", line 4, in <module>
    from parameterised2 import AddressBookUI
  File "/Users/craig/develop/reahl-examples/parameterised2/parameterised2.py", line 7, in <module>
    from reahl.web.layout import PageLayout
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/web/layout.py", line 29, in <module>
    from reahl.web.ui import Div, HTML5Page, Slot, Header, Footer
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/web/ui.py", line 46, in <module>
    from reahl.mailutil.rst import RestructuredText
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/reahl/mailutil/rst.py", line 20, in <module>
    import docutils.io
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/docutils/utils/__init__.py", line 21, in <module>
    from docutils.utils.error_reporting import ErrorOutput, SafeString
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/craig/VirtualEnvs/reahl_env/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by craig-reahl** [comment]
Some more context around the locale setting:

[Snippet from here](https://bugs.python.org/issue18378):

```
On Mac OS X 10.8 with the default language set to English (System Preferences | Language and Text), the default terminal application sets the LC_CTYPE environment variable to "UTF-8". If you run Python from the terminal and try to use locale.getdefaultlocate(), you get the following error:

> python
Python 2.7.2 (default, Oct 11 2012, 20:14:37)
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getdefaultlocale()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 496, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 428, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

(The stacktrace is from Python 2.7 but Python 3.3 suffers from the same problem.)

There are numerous workarounds for this problem (turning off the "Set locale environment variables on startup" option in the terminal settings, or adding "export LC_CTYPE=en_US.UTF8" to .bash_profile, selecting a language other than English in the Language & Text settings), but these require additional configuration from the user's side. 

I think that the more useful behavior is for Python to handle this behavior of the system and not crash, even though it doesn't strictly comply to the POSIX standard.

The attached patch (against current Python 3.4 master branch) is one possible fix.
```

**Comment by craig-reahl** [comment]
... on  a mac commandline I ran `locale`:

```
(reahl_env) iSparky:parameterised2 craig$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
which obviously confirms the issue.

then the suggested fix will solve the issue:

> Add some lines to your ~/.bash_profile then re-start bash (or re-login):

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Alternatively**, if you do not want to change your environment you could add this to your **etc/web.config.py**:

```
import locale
locale.setlocale(locale.LC_ALL,'en_US.UTF-8')

from parameterised2 import AddressBookUI
web.site_root = AddressBookUI
```
