### ISSUE TITLE
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#232]
I am getting this error when running my app on AWS. 

```
mod_wsgi (pid=3529): Exception occurred processing WSGI script '/opt/python/current/app/application.py'.
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 2703, in __call__
    self.config.web.session_class.initialise_web_session_on(context)
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/sqlalchemysupport/sqlalchemysupport.py", line 218, in nested_transaction
    self.commit()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/sqlalchemysupport/sqlalchemysupport.py", line 311, in commit
    Session.commit()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 156, in save_obj
    base_mapper, states, uowtransaction
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 286, in _organize_states_for_save
    states):
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1255, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in connection
    return self._connection_for_bind(bind, execution_options)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 398, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 398, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 1186, in _do_get
    (self.size(), self.overflow(), self._timeout), code="3o7r")
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)


```

reahl's sqlalchemysupport:
https://github.com/reahl/reahl/blob/master/reahl-sqlalchemysupport/reahl/sqlalchemysupport/sqlalchemysupport.py#L243
does not have options to expand create_args but it needs to have this so that I can configure the parameter in [the call to create_engine](https://docs.sqlalchemy.org/en/latest/core/pooling.html#connection-pool-configuration).

**Comment by IwanVosloo** [comment]
Sure, we can add a config setting with create_args dict.

**Comment by metaperl** [comment]
1. I'm confused about how my configuration should merge with the default. That is to say do I configure this with a dictionary and the values I define merge/override the default values?
1. I'm confused about what file this configuration data belongs in, primarily because [the code](https://github.com/IwanVosloo/reahl/blob/f5aa079349bc448c3a733e8e6029eab048f088ca/reahl-sqlalchemysupport/reahl/sqlalchemysupport/sqlalchemysupport.py#L50) references a file `sqlalchemy.config.py` and my existing sqlalchemy configuration is in `reahl.config.py`.

**Comment by IwanVosloo** [comment]
The plan with that commit was that your configuration will completely replace the default. Please note that was on an experimental branch of sorts. We ran into other issues with it...

`reahl.config.py` contains config for the base reahl system, part of which is the database connection URI and which orm_control to use. Typically, each component used has its own config, which is such a file. 

The fact that you can change sqlalchemy config by giving kwargs to the SqlAlchemyControl created in reahl.config.py is a bit of an inconsistency... Strictly speaking it is just supposed to say "use sqlalchemy", with more detailed settings of sqlalchemy in `sqlalchemy.config.py`.

The problem we have with my commit [f5aa079](https://github.com/IwanVosloo/reahl/commit/f5aa079349bc448c3a733e8e6029eab048f088ca) is that when a component has a test dependency on another, the test dependency's config is not read. We'll first have to find a way around that issue (see #237) because that proposed commit breaks our tests.

I think what we need to do here is to do #237 which will allow sqlalchemy config to go where it should. Then we need to add such config, and also change SqlAlchemyControl to NOT take any arguments... so that the current "debug" kwarg also becomes config in `sqlalchemy.config.py`. That is the way to make configuring sqlalchemy consistent with how all config for a given component works.

We won't be able to do that before the 5.0 release...and there's a lot of other things that need doing before we get there. I suggest that you create your own control class in the mean time and use that in your reahl.config.py instead of SqlAlchemyControl. Your changed class's `connect()` method can be a changed copy of the current [SqlAlchemyControl.connect](https://github.com/reahl/reahl/blob/831e333c32b38deccfc1ee41719f614c4c91c558/reahl-sqlalchemysupport/reahl/sqlalchemysupport/sqlalchemysupport.py#L234):

```
class MySqlAlchemyControl(SqlAlchemyControl):
    def connect(self):
        """Creates the SQLAlchemy Engine, bind it to the metadata and instrument the persisted classes 
           for the current reahlsystem.root_egg."""
        assert not self.connected
        context = ExecutionContext.get_context()

        config = context.config
        db_api_connection_creator = context.system_control.db_control.get_dbapi_connection_creator()

        create_args = {'pool_pre_ping': True, 'pool_size'=20, 'max_overflow'=0}   # Added kwargs
        if db_api_connection_creator:
            create_args['creator']=db_api_connection_creator

        self.engine = create_engine(config.reahlsystem.connection_uri, **create_args)
        self.engine.echo = self.echo
        self.engine.connect()
        metadata.bind = self.engine
        Session.configure(bind=self.engine)

        self.instrument_classes_for(config.reahlsystem.root_egg)
```

**Comment by metaperl** [comment]
In my source repo, I created `lib/patch_sqlalchemycontrol/py` and in that file I created a class as you described.

In `reahl.config.py` I did `from lib.patch_sqlalchemycontrol import SqlAlchemyControl` but that is not enough to change the QueuePool error I am getting:

```
"Traceback (most recent call last):" , "referer" : },
"  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/web/fw.py", line 2714, in __call__" , "referer" : },
"    self.config.web.session_class.initialise_web_session_on(context)" , "referer" : },
"  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__" , "referer" : },
"    next(self.gen)" , "referer" : },
"  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/sqlalchemysupport/sqlalchemysupport.py", line 221, in nested_transaction" , "referer" : },
"    self.commit()" , "referer" : },
"  File "/opt/python/run/venv/local/lib/python3.6/site-packages/reahl/sqlalchemysupport/sqlalchemysupport.py", line 314, in commit" , "referer" : },
"    Session.commit()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do" , "referer" : },
"    return getattr(self.registry(), name)(*args, **kwargs)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 954, in commit" , "referer" : },
"    self.transaction.commit()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit" , "referer" : },
"    self._prepare_impl()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl" , "referer" : },
"    self.session.flush()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2313, in flush" , "referer" : },
"    self._flush(objects)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush" , "referer" : },
"    transaction.rollback(_capture_exception=True)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__" , "referer" : },
"    compat.reraise(exc_type, exc_value, exc_tb)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise" , "referer" : },
"    raise value" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush" , "referer" : },
"    flush_context.execute()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute" , "referer" : },
"    rec.execute(self)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute" , "referer" : },
"    uow" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 156, in save_obj" , "referer" : },
"    base_mapper, states, uowtransaction" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 286, in _organize_states_for_save" , "referer" : },
"    states):" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1261, in _connections_for_states" , "referer" : },
"    connection = uowtransaction.transaction.connection(base_mapper)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in connection" , "referer" : },
"    return self._connection_for_bind(bind, execution_options)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 398, in _connection_for_bind" , "referer" : },
"    conn = self._parent._connection_for_bind(bind, execution_options)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 398, in _connection_for_bind" , "referer" : },
"    conn = self._parent._connection_for_bind(bind, execution_options)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind" , "referer" : },
"    conn = bind.contextual_connect()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect" , "referer" : },
"    self._wrap_pool_connect(self.pool.connect, None)," , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect" , "referer" : },
"    return fn()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 400, in connect" , "referer" : },
"    return _ConnectionFairy._checkout(self)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 788, in _checkout" , "referer" : },
"    fairy = _ConnectionRecord.checkout(pool)" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 529, in checkout" , "referer" : },
"    rec = pool._do_get()" , "referer" : },
"  File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 1186, in _do_get" , "referer" : },
"    (self.size(), self.overflow(), self._timeout), code="3o7r")" , "referer" : },
"sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)" , "referer" : },

```

**Comment by metaperl** [comment]
> I suggest that you create your own control class in the mean time and use that in your reahl.config.py

How is simply sticking this class in `reahl.config.py` going to change the behavior?

**Comment by IwanVosloo** [comment]
On 2019/01/25 21:52, Structure and Interpretation of Computer Programs 
wrote:
>     I suggest that you create your own control class in the mean time
>     and use that in your reahl.config.py
> 
> How is simply sticking this class in |reahl.config.py| going to change 
> the behavior?
> 


No, that alone indeed won't do it, you also need to put config in there 
so that your new class is used.  So in your reahl.config.py you ALSO need to have:

reahlsystem.orm_control = MySqlAlchemyControl()

**Comment by IwanVosloo** [comment]
BTW, I have just noticed that the standard https.conf file as per AWS instructions contains the line:

> WSGIDaemonProcess wsgi-ssl processes=1 threads=15 display-name=%{GROUP} 

I suspect this is what causes your issues with SqlAlchemy threads.

I suggest changing this to:

> WSGIDaemonProcess wsgi-ssl processes=1 threads=5 display-name=%{GROUP} 

For the load you need to handle that is still plenty. You can also consider upping the processes instead of the threads. That connection pool is per process.

**Comment by metaperl** [comment]
> I suggest that you create your own control class in the mean time and use that in your reahl.config.py instead of SqlAlchemyControl.

> reahlsystem.orm_control = MySqlAlchemyControl()

would you anticipate any variation in behavior between `MySqlAlchemyControl` being in the `reahl.config.py` file versus it being in another file and imported?

**Comment by IwanVosloo** [comment]
> would you anticipate any variation in behavior between `MySqlAlchemyControl` being in the `reahl.config.py` file versus it being in another file and imported?

No, I cant see that that should make a difference.
