### ISSUE TITLE
paypalsupport breaks when used with MySql

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#346]
One of the database columns defined in reahl-paypalsupport is declared to be Unicode without a size. This is not allowed when using MySql. Occurs when using reahl-paypalsupport 5.2

**Comment by craig-reahl** [comment]
This is the exception that is raised when running createdbtables:

`reahl createdbtables etc/
`
StackTrace:

```
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2209, in visit_VARCHAR
    raise exc.CompileError(
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/bin/reahl", line 8, in <module>
    sys.exit(ReahlCommandline.execute_one())
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/component/shelltools.py", line 206, in execute_one
    result = cls().do(sys.argv[1:])
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/component/shelltools.py", line 111, in do
   return self.execute(args)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/component/shelltools.py", line 226, in execute
    return super().execute(args)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/component/shelltools.py", line 170, in execute
    return command.do(args.command_args)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/component/shelltools.py", line 111, in do
    return self.execute(args)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/commands/prodshell.py", line 287, in execute
    return self.sys_control.create_db_tables()
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/component/dbutils.py", line 141, in create_db_tables
    return self.orm_control.create_db_tables(transaction, eggs_in_order)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/reahl/sqlalchemysupport/sqlalchemysupport.py", line 343, in create_db_tables
    metadata.create_all(bind=Session.connection())
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4864, in create_all
    bind._run_ddl_visitor(
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2119, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 849, in visit_metadata
    self.traverse_single(
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
    self.connection.execute(
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1295, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1384, in _execute_ddl
    compiled = ddl.compile(
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, **kw)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 32, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 4395, in visit_create_table
    util.raise_(
  File "/home/csparksfly/.virtualenvs/reahl-5.2.2/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.CompileError: (in table 'payment_paypal_order', column 'json_string'): VARCHAR requires a length on dialect mysql
```
