### ISSUE TITLE
Running "reahl" with a command that does not exist a weird error is reported

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#4]
This exception is reported, instead of a meaningfull error that should state that the command does not exist, and/or perhaps list the help for reahl. This occurs when not in a directory with a .reahlproject file.

Example of stacktrace:
Traceback (most recent call last):
  File "/home/craig/develop/.reahlworkspace/virtualenv.precise-dev/bin/reahl", line 9, in <module>
    load_entry_point('reahl-dev==2.0.1a1', 'console_scripts', 'reahl')()
  File "/home/craig/develop/reahl-windows/reahl-component/reahl/component/shelltools.py", line 115, in execute_one
    return_code = commandline.execute_command(command, line, options, parser)
  File "/home/craig/develop/reahl-windows/reahl-dev/reahl/dev/devshell.py", line 545, in execute_command
    retcode = alias_command.do(line)
  File "/home/craig/develop/reahl-windows/reahl-component/reahl/component/shelltools.py", line 57, in do
    return self.execute(options, args)
  File "/home/craig/develop/reahl-windows/reahl-dev/reahl/dev/devshell.py", line 244, in execute
    current_project = Project.from_file(self.workspace, os.getcwd())
  File "/home/craig/develop/reahl-windows/reahl-dev/reahl/dev/devdomain.py", line 1343, in from_file
    raise NotAValidProjectException(project_filename)
reahl.dev.exceptions.NotAValidProjectException: /tmp/.reahlproject

---

Imported from Launchpad using lp2gh.
- date created: 2014-03-11T08:32:31Z
- owner: craig-reahl
- assignee: craig-reahl
- the launchpad url was https://bugs.launchpad.net/bugs/1290739

**Comment by IwanVosloo** [comment]
(by iv)
Reproduced: it happens when you run "reahl unknowncommand" from inside a directory that is does not contain a .reahlproject file.
